[package]
name = "xrpc-rs"
version = "0.1.0"
edition = "2024"
authors = ["Jaemin Kim <geminik23@gmail.com>"]
description = "async RPC library optimized for shared memory communication"
license = "MIT"
repository = "https://github.com/geminik23/xrpc-rs"
keywords = ["rpc", "ipc", "async", "tokio", "shared-memory"]
readme = "README.md"

[dependencies]
bytes = "1.5"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"

[lib]
name = "xrpc"
path = "src/lib.rs"
